<?php

declare(strict_types=1);

namespace OpenTinker;

use Throwable;

/**
 * Generates an IDE helper stub describing each Eloquent model's real columns,
 * so `$user->` completes in scratch files. Same approach as
 * barryvdh/laravel-ide-helper's _ide_helper_models.php.
 *
 * Column and class names come from the database and app files, so only plain
 * identifiers make it into the generated PHP; anything else is skipped.
 */
final class ModelHints
{
    private const IDENTIFIER = '[A-Za-z_\x80-\xff][A-Za-z0-9_\x80-\xff]*';

    /** Laravel's cast classes and the type an attribute cast with them has. */
    private const CAST_CLASSES = [
        'Illuminate\Database\Eloquent\Casts\AsArrayObject' => '\Illuminate\Database\Eloquent\Casts\ArrayObject',
        'Illuminate\Database\Eloquent\Casts\AsCollection' => '\Illuminate\Support\Collection',
        'Illuminate\Database\Eloquent\Casts\AsEncryptedArrayObject' => '\Illuminate\Database\Eloquent\Casts\ArrayObject',
        'Illuminate\Database\Eloquent\Casts\AsEncryptedCollection' => '\Illuminate\Support\Collection',
        'Illuminate\Database\Eloquent\Casts\AsEnumArrayObject' => '\Illuminate\Database\Eloquent\Casts\ArrayObject',
        'Illuminate\Database\Eloquent\Casts\AsEnumCollection' => '\Illuminate\Support\Collection',
        'Illuminate\Database\Eloquent\Casts\AsStringable' => '\Illuminate\Support\Stringable',
    ];

    /** @return array{php: string, count: int, skipped: array<int, string>} */
    public static function generate(string $basePath): array
    {
        $models = [];
        $skipped = [];

        foreach (self::candidateClasses($basePath) as $class) {
            try {
                if (! \class_exists($class) || ! \is_subclass_of($class, \Illuminate\Database\Eloquent\Model::class)) {
                    continue;
                }

                $reflection = new \ReflectionClass($class);

                if ($reflection->isAbstract()) {
                    continue;
                }

                $models[$class] = self::properties($reflection->newInstanceWithoutConstructor());
            } catch (Throwable $throwable) {
                $skipped[] = $class . ': ' . $throwable->getMessage();
            }
        }

        return self::render($models, $skipped);
    }

    /**
     * @param array<string, array<string, string>> $models class => [column => type]
     * @param array<int, string> $skipped
     * @return array{php: string, count: int, skipped: array<int, string>}
     */
    public static function render(array $models, array $skipped = []): array
    {
        \ksort($models);
        $out = "<?php\n\n// @formatter:off\n// Generated by OpenTinker from your database schema. Regenerate with\n// \"OpenTinker: Generate Model Hints\". Do not edit or commit this file.\n\n";
        $count = 0;

        foreach ($models as $class => $properties) {
            if (! self::isClassName($class)) {
                $skipped[] = "{$class}: not a plain class name";
                continue;
            }

            $class = \ltrim($class, '\\');
            $position = \strrpos($class, '\\');
            $namespace = $position === false ? '' : \substr($class, 0, $position);
            $short = $position === false ? $class : \substr($class, $position + 1);
            $out .= "namespace {$namespace} {\n    /**\n";

            foreach ($properties as $name => $type) {
                if (! \preg_match('/^' . self::IDENTIFIER . '$/', (string) $name) || ! self::isType($type)) {
                    $skipped[] = "{$class}: skipped a column with an unusual name or type";
                    continue;
                }

                $out .= "     * @property {$type} \${$name}\n";
            }

            $out .= "     * @method static \\Illuminate\\Database\\Eloquent\\Builder<{$short}> query()\n";
            $out .= "     * @mixin \\Illuminate\\Database\\Eloquent\\Builder<{$short}>\n";
            $out .= "     */\n    class {$short} {}\n}\n\n";
            $count++;
        }

        return ['php' => $out, 'count' => $count, 'skipped' => \array_slice($skipped, 0, 20)];
    }

    /** @return array<int, string> */
    private static function candidateClasses(string $basePath): array
    {
        $classes = [];
        $directory = $basePath . '/app/Models';

        if (! \is_dir($directory)) {
            return [];
        }

        $files = new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($directory, \FilesystemIterator::SKIP_DOTS));

        foreach ($files as $file) {
            if (! $file instanceof \SplFileInfo || $file->getExtension() !== 'php') {
                continue;
            }

            $class = self::classIn((string) \file_get_contents($file->getPathname()));

            if ($class !== null) {
                $classes[] = $class;
            }

            if (\count($classes) >= 500) {
                break;
            }
        }

        return $classes;
    }

    private static function classIn(string $source): ?string
    {
        $namespace = \preg_match('/^namespace\s+([^;{\s]+)\s*[;{]/m', $source, $match) ? \trim($match[1]) : '';

        if (! \preg_match('/^\s*(?:final\s+|abstract\s+|readonly\s+)*class\s+(' . self::IDENTIFIER . ')/m', $source, $classMatch)) {
            return null;
        }

        return ($namespace !== '' ? $namespace . '\\' : '') . $classMatch[1];
    }

    /** @return array<string, string> */
    private static function properties(\Illuminate\Database\Eloquent\Model $model): array
    {
        $schema = \Illuminate\Support\Facades\Schema::connection($model->getConnectionName());
        $casts = $model->getCasts();
        $properties = [];

        if (\method_exists($schema, 'getColumns')) {
            foreach ($schema->getColumns($model->getTable()) as $column) {
                $type = self::phpType((string) ($column['type_name'] ?? $column['type'] ?? ''), $casts[$column['name']] ?? null);
                $properties[$column['name']] = ($column['nullable'] ?? false) && $type !== 'mixed' ? $type . '|null' : $type;
            }
        } else {
            foreach ($schema->getColumnListing($model->getTable()) as $name) {
                $properties[$name] = self::phpType($schema->getColumnType($model->getTable(), $name), $casts[$name] ?? null);
            }
        }

        return $properties;
    }

    private static function phpType(string $databaseType, mixed $cast): string
    {
        if (\is_string($cast) && $cast !== '') {
            // 'decimal:2', 'datetime:Y-m-d', 'encrypted:array', 'AsCollection:App\Foo'
            [$name, $argument] = \array_pad(\explode(':', $cast, 2), 2, '');
            $builtin = self::builtinCast(\strtolower($name) === 'encrypted' ? ($argument !== '' ? $argument : 'string') : $name);

            return $builtin ?? self::classCast(\ltrim($name, '\\'));
        }

        $type = \strtolower($databaseType);

        return match (true) {
            \str_contains($type, 'int') => 'int',
            \str_contains($type, 'bool') => 'bool',
            // decimal and numeric columns arrive as strings, so they fall through to string.
            \str_contains($type, 'float') || \str_contains($type, 'double') || \str_contains($type, 'real') => 'float',
            \str_contains($type, 'json') => 'array',
            \str_contains($type, 'date') || \str_contains($type, 'time') => '\\Illuminate\\Support\\Carbon',
            default => 'string',
        };
    }

    private static function builtinCast(string $cast): ?string
    {
        return match (\strtolower($cast)) {
            'int', 'integer', 'timestamp' => 'int',
            'real', 'float', 'double' => 'float',
            'decimal', 'string', 'hashed' => 'string',
            'bool', 'boolean' => 'bool',
            'array', 'json' => 'array',
            'object' => '\\stdClass',
            'collection' => '\\Illuminate\\Support\\Collection',
            'date', 'datetime', 'custom_datetime' => '\\Illuminate\\Support\\Carbon',
            'immutable_date', 'immutable_datetime' => '\\Carbon\\CarbonImmutable',
            default => null,
        };
    }

    /** The attribute type for a cast given as a class name, keeping the class's own case. */
    private static function classCast(string $class): string
    {
        if (isset(self::CAST_CLASSES[$class])) {
            return self::CAST_CLASSES[$class];
        }

        // Enums and value objects that provide their own caster are the attribute's type.
        if (\enum_exists($class) || \is_subclass_of($class, \Illuminate\Contracts\Database\Eloquent\Castable::class)) {
            return '\\' . $class;
        }

        // A caster class: its get() return type, when declared, is the attribute's type.
        if (\is_subclass_of($class, \Illuminate\Contracts\Database\Eloquent\CastsAttributes::class)) {
            $type = (new \ReflectionMethod($class, 'get'))->getReturnType();

            if ($type instanceof \ReflectionNamedType && ! $type->isBuiltin()) {
                return '\\' . $type->getName();
            }

            if ($type instanceof \ReflectionNamedType && \in_array($type->getName(), ['int', 'float', 'string', 'bool', 'array'], true)) {
                return $type->getName();
            }
        }

        return 'mixed';
    }

    private static function isClassName(string $name): bool
    {
        return (bool) \preg_match('/^\\\\?' . self::IDENTIFIER . '(?:\\\\' . self::IDENTIFIER . ')*$/', $name);
    }

    /** A type made of class names and builtins joined by `|`, as phpType() produces. */
    private static function isType(string $type): bool
    {
        foreach (\explode('|', $type) as $part) {
            if (! self::isClassName($part)) {
                return false;
            }
        }

        return true;
    }
}
