<?php

declare(strict_types=1);

namespace OpenTinker;

use Throwable;

/**
 * Generates an IDE helper stub describing each Eloquent model's real columns,
 * so `$user->` completes in scratch files. Same approach as
 * barryvdh/laravel-ide-helper's _ide_helper_models.php.
 */
final class ModelHints
{
    /** @return array{php: string, count: int, skipped: array<int, string>} */
    public static function generate(string $basePath): array
    {
        $models = [];
        $skipped = [];

        foreach (self::candidateClasses($basePath) as $class) {
            try {
                if (! \class_exists($class) || ! \is_subclass_of($class, \Illuminate\Database\Eloquent\Model::class)) {
                    continue;
                }

                $reflection = new \ReflectionClass($class);

                if ($reflection->isAbstract()) {
                    continue;
                }

                $models[$class] = self::properties($reflection->newInstanceWithoutConstructor());
            } catch (Throwable $throwable) {
                $skipped[] = $class . ': ' . $throwable->getMessage();
            }
        }

        \ksort($models);
        $out = "<?php\n\n// @formatter:off\n// Generated by OpenTinker from your database schema. Regenerate with\n// \"OpenTinker: Generate Model Hints\". Do not edit or commit this file.\n\n";

        foreach ($models as $class => $properties) {
            $namespace = \substr($class, 0, (int) \strrpos($class, '\\'));
            $short = \substr($class, (int) \strrpos($class, '\\') + 1);
            $out .= "namespace {$namespace} {\n    /**\n";

            foreach ($properties as $name => $type) {
                $out .= "     * @property {$type} \${$name}\n";
            }

            $out .= "     * @method static \\Illuminate\\Database\\Eloquent\\Builder<{$short}> query()\n";
            $out .= "     * @mixin \\Illuminate\\Database\\Eloquent\\Builder<{$short}>\n";
            $out .= "     */\n    class {$short} {}\n}\n\n";
        }

        return ['php' => $out, 'count' => \count($models), 'skipped' => \array_slice($skipped, 0, 20)];
    }

    /** @return array<int, string> */
    private static function candidateClasses(string $basePath): array
    {
        $classes = [];
        $directories = [$basePath . '/app/Models'];

        foreach ($directories as $directory) {
            if (! \is_dir($directory)) {
                continue;
            }

            $files = new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($directory, \FilesystemIterator::SKIP_DOTS));

            foreach ($files as $file) {
                if (! $file instanceof \SplFileInfo || $file->getExtension() !== 'php') {
                    continue;
                }

                $class = self::classIn((string) \file_get_contents($file->getPathname()));

                if ($class !== null) {
                    $classes[] = $class;
                }

                if (\count($classes) >= 500) {
                    break 2;
                }
            }
        }

        return $classes;
    }

    private static function classIn(string $source): ?string
    {
        $namespace = \preg_match('/^namespace\s+([^;]+);/m', $source, $match) ? \trim($match[1]) : '';

        if (! \preg_match('/^\s*(?:final\s+|abstract\s+|readonly\s+)*class\s+([A-Za-z_][A-Za-z0-9_]*)/m', $source, $classMatch)) {
            return null;
        }

        return ($namespace !== '' ? $namespace . '\\' : '') . $classMatch[1];
    }

    /** @return array<string, string> */
    private static function properties(\Illuminate\Database\Eloquent\Model $model): array
    {
        $schema = \Illuminate\Support\Facades\Schema::connection($model->getConnectionName());
        $casts = $model->getCasts();
        $properties = [];

        if (\method_exists($schema, 'getColumns')) {
            foreach ($schema->getColumns($model->getTable()) as $column) {
                $type = self::phpType((string) ($column['type_name'] ?? $column['type'] ?? ''), $casts[$column['name']] ?? null);
                $properties[$column['name']] = ($column['nullable'] ?? false) ? $type . '|null' : $type;
            }
        } else {
            foreach ($schema->getColumnListing($model->getTable()) as $name) {
                $properties[$name] = self::phpType($schema->getColumnType($model->getTable(), $name), $casts[$name] ?? null);
            }
        }

        return $properties;
    }

    private static function phpType(string $databaseType, mixed $cast): string
    {
        if (\is_string($cast)) {
            $cast = \strtolower(\explode(':', $cast)[0]);

            return match (true) {
                \in_array($cast, ['int', 'integer', 'timestamp'], true) => 'int',
                \in_array($cast, ['real', 'float', 'double', 'decimal'], true) => 'float',
                \in_array($cast, ['bool', 'boolean'], true) => 'bool',
                \in_array($cast, ['array', 'json', 'object'], true) => 'array',
                \in_array($cast, ['collection', 'encrypted:collection', 'as_collection'], true) => '\\Illuminate\\Support\\Collection',
                \in_array($cast, ['date', 'datetime', 'immutable_date', 'immutable_datetime', 'custom_datetime'], true) => '\\Illuminate\\Support\\Carbon',
                \class_exists($cast) => '\\' . \ltrim($cast, '\\'),
                default => 'string',
            };
        }

        $type = \strtolower($databaseType);

        return match (true) {
            \str_contains($type, 'int') => 'int',
            \str_contains($type, 'bool') => 'bool',
            \str_contains($type, 'float') || \str_contains($type, 'double') || \str_contains($type, 'decimal') || \str_contains($type, 'numeric') || \str_contains($type, 'real') => 'float',
            \str_contains($type, 'json') => 'array',
            \str_contains($type, 'date') || \str_contains($type, 'time') => '\\Illuminate\\Support\\Carbon',
            default => 'string',
        };
    }
}
