// Stitches worker/src/*.php and worker/main.php into the single dist/worker.php
// the extension ships to each runtime. Each source file becomes a braced
// `namespace OpenTinker { … }` block so its own `use` imports stay valid.
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

export const WORKER_SOURCES = [
    'src/Protocol.php',
    'src/TempDir.php',
    'src/SourceCode.php',
    'src/FileImports.php',
    'src/ImportAliases.php',
    'src/StatementSplitter.php',
    'src/TokenRewriter.php',
    'src/Values.php',
    'src/DumpCapture.php',
    'src/SqlCollector.php',
    'src/ErrorFormatter.php',
    'src/ScopeReader.php',
    'src/SideEffects.php',
    'src/Runner.php',
    'src/Forker.php',
    'src/ModelHints.php',
    'main.php',
];

function toBlock(source, file) {
    const body = source.replace(/^<\?php\s*/, '').replace(/^declare\(strict_types=1\);\s*/m, '');
    const namespace = /^namespace OpenTinker;\s*$/m;
    if (!namespace.test(body)) {
        throw new Error(`${file} must declare "namespace OpenTinker;"`);
    }
    return `// ---- ${file} ----\nnamespace OpenTinker {\n${body.replace(namespace, '').trim()}\n}\n`;
}

export async function buildWorker(outFile = join(root, 'dist', 'worker.php')) {
    const blocks = [];
    for (const file of WORKER_SOURCES) {
        blocks.push(toBlock(await readFile(join(root, 'worker', file), 'utf8'), file));
    }
    const output = `<?php

declare(strict_types=1);

/*
 * OpenTinker worker — generated by scripts/build-worker.mjs from worker/src.
 * Edit the sources, not this file.
 *
 * Boots the host application, embeds PsySH and speaks newline-delimited JSON
 * over stdin/stdout. It needs nothing beyond the host app's vendor/ directory.
 */

${blocks.join('\n')}`;
    await mkdir(dirname(outFile), { recursive: true });
    await writeFile(outFile, output, 'utf8');
    return outFile;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
    const out = await buildWorker(process.argv[2]);
    console.log(`worker: ${out}`);
}
